## Sample configuration
test:
    stage: test # this is just a name
    local: true
    branch: developer
    dump_db: false # if true then a db dump is created during deployment
    deploy_path: /var/www/webroot # where to deploy files
    locales: en_US de_CH # locales for setup:static-content:deploy
    # Directories that should not be newly created upon deployment.
    # Symlinks to corresponding dirs in {deploy_path}/shared/ will be created.
    shared_dirs:
        - var
        - pub/media
        - extensions-client
    shared_files: # same as directories but files
        - app/etc/env.php
        - pub/sitemap.xml

production:
    stage: production
    local: true
    branch: master
    dump_db: true
    deploy_path: /var/www/webroot
    locales: en_US de_CH es_ES
    shared_dirs:
        - var
        - pub/media
        - extensions-client
    shared_files:
        - app/etc/env.php
        - pub/sitemap.xml
